export const CHEF_LOGIN_REQUEST = 'CHEF_LOGIN_REQUEST'
export const CHEF_LOGIN_SUCCESS = 'CHEF_LOGIN_SUCCESS'
export const CHEF_LOGIN_FAILURE = 'CHEF_LOGIN_FAILURE'

export const CHEF_LOGOUT = 'CHEF_LOGOUT'

export const CHEF_REGISTER_REQUEST = 'CHEF_REGISTER_REQUEST'
export const CHEF_REGISTER_SUCCESS = 'CHEF_REGISTER_SUCCESS'
export const CHEF_REGISTER_FAILURE = 'CHEF_REGISTER_FAILURE'

export const CHEF_DETAILS_REQUEST = 'CHEF_DETAILS_REQUEST'
export const CHEF_DETAILS_SUCCESS = 'CHEF_DETAILS_SUCCESS'
export const CHEF_DETAILS_FAILURE = 'CHEF_DETAILS_FAILURE'
export const CHEF_DETAILS_RESET = 'CHEF_DETAILS_RESET'

export const CHEF_UPDATE_PROFILE_REQUEST = 'CHEF_UPDATE_PROFILE_REQUEST'
export const CHEF_UPDATE_PROFILE_SUCCESS = 'CHEF_UPDATE_PROFILE_SUCCESS'
export const CHEF_UPDATE_PROFILE_FAILURE = 'CHEF_UPDATE_PROFILE_FAILURE'
export const CHEF_UPDATE_PROFILE_RESET = 'CHEF_UPDATE_PROFILE_RESET'
