export const CHEF_LIST_REQUEST = 'CHEF_LIST_REQUEST'
export const CHEF_LIST_SUCCESS = 'CHEF_LIST_SUCCESS'
export const CHEF_LIST_FAILURE = 'CHEF_LIST_FAILURE'

export const CHEF_PUBLIC_DETAILS_REQUEST = 'CHEF_PUBLIC_DETAILS_REQUEST'
export const CHEF_PUBLIC_DETAILS_SUCCESS = 'CHEF_PUBLIC_DETAILS_SUCCESS'
export const CHEF_PUBLIC_DETAILS_FAILURE = 'CHEF_PUBLIC_DETAILS_FAILURE'
export const CHEF_PUBLIC_DETAILS_RESET = 'CHEF_PUBLIC_DETAILS_RESET'
