export const COOKBOOK_CREATE_REQUEST = 'COOKBOOK_CREATE_REQUEST'
export const COOKBOOK_CREATE_SUCCESS = 'COOKBOOK_CREATE_SUCCESS'
export const COOKBOOK_CREATE_FAILURE = 'COOKBOOK_CREATE_FAILURE'
export const COOKBOOK_CREATE_RESET= 'COOKBOOK_CREATE_RESET'

export const COOKBOOK_MYLIST_REQUEST = 'COOKBOOK_MYLIST_REQUEST'
export const COOKBOOK_MYLIST_SUCCESS = 'COOKBOOK_MYLIST_SUCCESS'
export const COOKBOOK_MYLIST_FAILURE = 'COOKBOOK_MYLIST_FAILURE'
