export const GROCERY_LIST_EMAIL_REQUEST = 'GROCERY_LIST_EMAIL_REQUEST'
export const GROCERY_LIST_EMAIL_SUCCESS = 'GROCERY_LIST_EMAIL_SUCCESS'
export const GROCERY_LIST_EMAIL_FAILURE = 'GROCERY_LIST_EMAIL_FAILURE'

export const GROCERY_LIST_TEXT_REQUEST = 'GROCERY_LIST_TEXT_REQUEST'
export const GROCERY_LIST_TEXT_SUCCESS = 'GROCERY_LIST_TEXT_SUCCESS'
export const GROCERY_LIST_TEXT_FAILURE = 'GROCERY_LIST_TEXT_FAILURE'
