export const GROCERY_LIST_EMAIL_REQUEST = 'GROCERY_LIST_EMAIL_REQUEST'
export const GROCERY_LIST_EMAIL_SUCCESS = 'GROCERY_LIST_EMAIL_SUCCESS'
export const GROCERY_LIST_EMAIL_FAILURE = 'GROCERY_LIST_EMAIL_FAILURE'
