export const RECIPE_LIST_REQUEST = 'RECIPE_LIST_REQUEST'
export const RECIPE_LIST_SUCCESS = 'RECIPE_LIST_SUCCESS'
export const RECIPE_LIST_FAILURE = 'RECIPE_LIST_FAILURE'

export const RECIPE_DETAILS_REQUEST = 'RECIPE_DETAILS_REQUEST'
export const RECIPE_DETAILS_SUCCESS = 'RECIPE_DETAILS_SUCCESS'
export const RECIPE_DETAILS_FAILURE = 'RECIPE_DETAILS_FAILURE'

export const RECIPE_DELETE_REQUEST = 'RECIPE_DELETE_REQUEST'
export const RECIPE_DELETE_SUCCESS = 'RECIPE_DELETE_SUCCESS'
export const RECIPE_DELETE_FAILURE = 'RECIPE_DELETE_FAILURE'

export const RECIPE_CREATE_REQUEST = 'RECIPE_CREATE_REQUEST'
export const RECIPE_CREATE_SUCCESS = 'RECIPE_CREATE_SUCCESS'
export const RECIPE_CREATE_FAILURE = 'RECIPE_CREATE_FAILURE'
export const RECIPE_CREATE_RESET= 'RECIPE_CREATE_RESET'

export const RECIPE_UPDATE_REQUEST = 'RECIPE_UPDATE_REQUEST'
export const RECIPE_UPDATE_SUCCESS = 'RECIPE_UPDATE_SUCCESS'
export const RECIPE_UPDATE_FAILURE = 'RECIPE_UPDATE_FAILURE'
export const RECIPE_UPDATE_RESET= 'RECIPE_UPDATE_RESET'

export const RECIPE_CREATE_UPVOTE_REQUEST = 'RECIPE_CREATE_UPVOTE_REQUEST'
export const RECIPE_CREATE_UPVOTE_SUCCESS = 'RECIPE_CREATE_UPVOTE_SUCCESS'
export const RECIPE_CREATE_UPVOTE_FAILURE = 'RECIPE_CREATE_UPVOTE_FAILURE'
export const RECIPE_CREATE_UPVOTE_RESET= 'RECIPE_CREATE_UPVOTE_RESET'

export const RECIPE_CREATE_DOWNVOTE_REQUEST = 'RECIPE_CREATE_DOWNVOTE_REQUEST'
export const RECIPE_CREATE_DOWNVOTE_SUCCESS = 'RECIPE_CREATE_DOWNVOTE_SUCCESS'
export const RECIPE_CREATE_DOWNVOTE_FAILURE = 'RECIPE_CREATE_DOWNVOTE_FAILURE'
export const RECIPE_CREATE_DOWNVOTE_RESET= 'RECIPE_CREATE_DOWNVOTE_RESET'

export const RECIPE_SAVE_REQUEST = 'RECIPE_SAVE_REQUEST'
export const RECIPE_SAVE_SUCCESS = 'RECIPE_SAVE_SUCCESS'
export const RECIPE_SAVE_FAILURE = 'RECIPE_SAVE_FAILURE'
export const RECIPE_SAVE_RESET= 'RECIPE_SAVE_RESET'
