const Countries = [
  ["1", ""],
  ["2", "Afghanistan"],
  ["3", "Albania"],
  ["4", "Algeria"],
  ["5", "Angola"],
  ["6", "Argentina"],
  ["7", "Armenia"],
  ["8", "Australia"],
  ["9", "Austria"],
  ["10", "Azerbaijan"],
  ["11", "Bahrain"],
  ["12", "Bangladesh"],
  ["13", "Belarus"],
  ["14", "Belgium"],
  ["15", "Belize"],
  ["16", "Benin"],
  ["17", "Bhutan"],
  ["18", "Bolivia"],
  ["19", "Bosnia and Herzegovina"],
  ["20", "Botswana"],
  ["21", "Brazil"],
  ["22", "Brunei"],
  ["23", "Bulgaria"],
  ["24", "Burkina Faso"],
  ["25", "Burundi"],
  ["26", "Cote d'Ivoire"],
  ["27", "Cambodia"],
  ["28", "Cameroon"],
  ["29", "Canada"],
  ["30", "Central African Republic"],
  ["31", "Chad"],
  ["32", "Chile"],
  ["33", "China"],
  ["34", "Colombia"],
  ["35", "Congo"],
  ["36", "Costa Rica"],
  ["37", "Croatia"],
  ["38", "Cuba"],
  ["39", "Czech Republican"],
  ["40", "Denmark"],
  ["41", "Dominican Republican"],
  ["42", "Ecuador"],
  ["43", "Egypt"],
  ["44", "El Salvador"],
  ["45", "Estonia"],
  ["46", "Ethiopia"],
  ["47", "Finland"],
  ["48", "France"],
  ["49", "Gabon"],
  ["50", "Gambia"],
  ["51", "Georiga"],
  ["52", "Germany"],
  ["53", "Ghana"],
  ["54", "Greece"],
  ["55", "Guatemala"],
  ["56", "Guinea"],
  ["57", "India"],
  ["58", "Italy"],
  ["59", "Myanmar"],
  ["60", "Thailand"],
]

export default Countries;
